services:
  database:
    image: postgres
    restart: unless-stopped # restart the container unless it was explicitly stopped (Development)
    shm_size: 128mb # Shared memory size
    volumes:
      - postgres_telegram_banking:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5433:5432"

    logging:
      driver: "json-file" # Stores logs in JSON format in host system
      options:
        max-size: "10m" # Maximum size of log file
        max-file: "3" # Maximum number of log files

  broker:
    image: rabbitmq:3.11-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq




volumes:
  postgres_telegram_banking:
  rabbitmq_data: