"""added_telegram_id_and_balance_to_user

Revision ID: 26f377c186b9
Revises: edf2cc640657
Create Date: 2025-05-11 16:37:06.809225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '26f377c186b9'
down_revision: Union[str, None] = 'edf2cc640657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_column('user', 'email')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'balance')
    op.drop_column('user', 'telegram_id')
    # ### end Alembic commands ###