"""modofied telegram_id on user model

Revision ID: 3db8b254d47c
Revises: 3049092373df
Create Date: 2025-05-19 13:30:10.386756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3db8b254d47c'
down_revision: Union[str, None] = '3049092373df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="1372820260"))
    op.alter_column('user', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    
    op.alter_column("user", "chat_id", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'chat_id')
    # ### end Alembic commands ###