"""add email to user model

Revision ID: 5e5066ffc46f
Revises: ffa44cdee20f
Create Date: 2025-05-12 03:25:06.562769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5e5066ffc46f'
down_revision: Union[str, None] = 'ffa44cdee20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    op.execute("UPDATE \"user\" SET email = 'user_' || id || '@placeholder.com' WHERE email IS NULL")

    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###