"""added a conversation model and upated the foreign key coontraint casacde on deva

Revision ID: 7ff75d275708
Revises: 6d684a3c1367
Create Date: 2025-05-14 11:55:18.561190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7ff75d275708'
down_revision: Union[str, None] = '6d684a3c1367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('HUMAN', 'ASSISTANT', 'SYSTEM', name='conversationrole'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_constraint('dva_user_id_fkey', 'dva', type_='foreignkey')
    op.create_foreign_key(None, 'dva', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dva', type_='foreignkey')
    op.create_foreign_key('dva_user_id_fkey', 'dva', 'user', ['user_id'], ['id'])
    op.drop_table('conversation')
    # ### end Alembic commands ###