"""updated message role type to text on message model

Revision ID: 9319ddbb562c
Revises: ca077586c783
Create Date: 2025-05-14 13:17:11.282661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9319ddbb562c'
down_revision: Union[str, None] = 'ca077586c783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'role',
               existing_type=postgresql.ENUM('HUMAN', 'ASSISTANT', 'SYSTEM', name='messagerole'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    
    op.execute("DROP TYPE IF EXISTS messagerole;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('HUMAN', 'ASSISTANT', 'SYSTEM', name='messagerole'),
               nullable=True)
    # ### end Alembic commands ###