"""updated conversation model removed unique on user

Revision ID: ca077586c783
Revises: d315e9bc2cd3
Create Date: 2025-05-14 12:33:01.021512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'ca077586c783'
down_revision: Union[str, None] = 'd315e9bc2cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_user_id_key', 'conversation', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('conversation_user_id_key', 'conversation', ['user_id'])
    # ### end Alembic commands ###