"""removed_all_models_apart_from_users

Revision ID: edf2cc640657
Revises: ef4c96f895ea
Create Date: 2025-05-11 15:51:20.818358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edf2cc640657'
down_revision: Union[str, None] = 'ef4c96f895ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    connection.execute(sa.text("DROP TABLE quiz CASCADE"))
    connection.execute(sa.text("DROP TABLE questions CASCADE"))
    op.add_column('user', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'phone_number')
    op.create_table('questions',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], name='questions_quiz_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    sa.UniqueConstraint('question', name='questions_question_key')
    )
    op.create_table('quiz',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='quiz_pkey'),
    sa.UniqueConstraint('name', name='quiz_name_key')
    )
    # ### end Alembic commands ###