"""added messaged model

Revision ID: f5cbaba3e401
Revises: 7ff75d275708
Create Date: 2025-05-14 12:23:51.571590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5cbaba3e401'
down_revision: Union[str, None] = '7ff75d275708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('HUMAN', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('conversation', 'content')
    op.drop_column('conversation', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('role', postgresql.ENUM('HUMAN', 'ASSISTANT', 'SYSTEM', name='conversationrole'), autoincrement=False, nullable=True))
    op.add_column('conversation', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('message')
    # ### end Alembic commands ###